#!/bin/sh

__sync_check() {
	cmd="zfs list | awk '{print \$1}' | egrep \"^$poolsource/$filesystem\$\" 2>&1 >/dev/null"
	eval $cmd
	if [ $? -ne 0 ]; then
		[ -z $CRON ] && echo "Error: zfs filesystem $poolsource/$filesystem does not exist....bye"
		[ -f "$pid" ] && rm -f "$pid"
		exit 1
	fi
	cmd="ssh $remote id 2>&1 >/dev/null"
	eval $cmd
	if [ $? -ne 0 ]; then
		[ -z $CRON ] && echo "could not execute remote test command: $cmd please fix!...bye"
		[ -f "$pid" ] && rm -f "$pid"
		exit 2
	fi
	cmd="ssh $remote zfs list | awk '{print \$1}' |  egrep \"^$pooldest/$filesystem\$\" 2>&1 >/dev/null"
	eval $cmd
	if [ $? -ne 0 ]; then
		[ -z $CRON ] && echo "Warning: zfs remote filesystem $pooldest/$filesystem does not exist"
	fi
	__sync_last_remote_syncsnapshot_exist 1 ${pooldest} ${filesystem} ${remote}
}

__sync_create_snapshot() {
	cmd="zfs snapshot -r $1/$2@sync-$3"
	eval $cmd
	if [ $? -ne 0  ]; then
		[ -z $CRON ] && echo "Error: snapshot failed... bye" >&2
		[ -f "$pid" ] && rm -f "$pid"
		exit 1
	fi

	__sync_last_snapshot 1 $1 $2
	if [ "${last}" == "${curtime}" ]; then
		[ -z $CRON ] && echo "Snapshot created: OK"
	else
		[ -z $CRON ] && echo "Snapshot failed: ${last} - ${curtime}!" >&2
		[ -f "$pid" ] && rm -f "$pid"
		exit 1
	fi
}

__sync_last_remote_syncsnapshot_exist() {
	cmd="zfs list -H -r -s creation -t snapshot -o name $2/$3|tail -$1|head -1"
	last=$(ssh root@$4 $cmd)
	[ -z "$last" ] && return
	echo $last | grep "@sync" 2>&1 >/dev/null
	if [ ! $? -eq 0 ]; then
		[ -z $CRON ] && echo "last remote snapshot is not of type @sync.....bye" 
		[ -f "$pid" ] && rm -f "$pid"
		exit 3
	fi
}

__sync_last_snapshot() {
	cmd="zfs list -H -r -s creation -t snapshot -o name $2/$3|tail -$1|head -1|awk '/@sync-/ { split(\$1,snapshot,\"@\"); print substr(snapshot[2],6) }'"

	if [ "$4" == "" ]; then
		last=$(eval $cmd)
	else
		last=$(ssh root@$4 $cmd)
	fi
}

__sync_sync() {
	__sync_last_snapshot 1 $2 $3 $4
	last_remote=${last}
	[ -z $CRON ] && echo "last remote snapshot: ${last_remote}"
	__sync_last_snapshot 1 $1 $3
	last_local=${last}
	[ -z $CRON ] && echo "last local snapshot: ${last_local}"

	if [ "$last_remote" == "" ]; then
		[ -z $CRON ] && echo "no remote snapshot: full send->receive"
		cmda="zfs send -R $1/$3@sync-${last_local}"
		cmdb="zfs receive -F -d $2"
		cmd="${cmda} | ssh root@$4 ${cmdb} 2>&1 >/dev/null"
		[ -z $CRON ] && echo "running: $cmd"
		eval $cmd
		return
	fi

	[ -z $CRON ] && echo "Syncing: to ${last_local} from ${last_remote}"

	cmda="zfs send -R -i $1/$3@sync-${last_remote} $1/$3@sync-${last_local}"
	cmdb="zfs receive -F -d $2"
	cmd="${cmda} | ssh root@$4 ${cmdb} 2>&1 > /dev/null"

	eval $cmd
}

__sync_cleanup() {
	__sync_last_snapshot 1 $2 $3 $4
	last_remote=${last}
	__sync_last_snapshot 1 $1 $3
	last_local=${last}

	[ -z $CRON ] && echo "Start cleanup local: ${last_local}, remote: ${last_remote}"	

	if [ "${last_local}" != "${last_remote}" ]; then
		[ -z $CRON ] && echo "Snapshots do not match after sync; local: ${last_local}, remote: ${last_remote}" >&2
		[ -f "$pid" ] && rm -f "$pid"
		exit 1
	fi

	for destroy in $(zfs list -H -r -s creation -t snapshot -o name $1/$3 | grep @sync- | grep -v @sync-${last_local}); do
		[ -z $CRON ] && echo "Destroying local: ${destroy}"
		zfs destroy ${destroy}
	done

	for destroy in $(ssh root@$4 zfs list -H -r -s creation -t snapshot -o name $2/$3 | grep @sync- | grep -v @sync-${last_remote}); do
		[ -z $CRON ] && echo "Destroying remote: ${destroy}"
		ssh root@$4 zfs destroy ${destroy}
	done
}

__sync () {
	export CRON=$2

	curmin=$(date "+%M")

	for dataset in $(zfs get -s local -o name iohyve:sync | grep -v NAME); do
		config=$(zfs get -H -s local -o value iohyve:sync $dataset)
		poolsource=$( echo $config | cut -d ' ' -f 1 )
		pooldest=$(   echo $config | cut -d ' ' -f 2 )
		filesystem=$( echo $config | cut -d ' ' -f 3 ) 
		interval=$(   echo $config | cut -d ' ' -f 4 )
		remote=$(     echo $config | cut -d ' ' -f 5 )
		curtime=$(date +%y%m%d%H%M)

		pid="/var/run/$(echo $filesystem | sed -e 's/\//-/g').zfssync"

		if [ $interval -ne $curmin ]; then
			[ -z $CRON ] && echo "This sync only happens at $interval past the hour...."
			exit 0
		fi

		if [ -f "$pid" ]; then
			echo "echo already running for this fs (found $pid)"
			exit 1
		else
			touch $pid 
		fi

		if [ -z $CRON ]; then
			echo "Parameters"
			echo "=========="
			echo "Source: ${poolsource}"
			echo "Dest:   ${pooldest}"
			echo "FileS:  ${filesystem}"
			echo "Remote: ${remote}"
			echo "Snap:   ${curtime}"
			echo
		fi

		# Check
		__sync_check

		# Create snapshot
		__sync_create_snapshot ${poolsource} ${filesystem} ${curtime}

		# Sync incremental
		__sync_sync ${poolsource} ${pooldest} ${filesystem} ${remote}

		# Clean up local
		__sync_cleanup ${poolsource} ${pooldest} ${filesystem} ${remote}

		# remove pid
		[ -f "$pid" ] && rm "$pid"
	done
}

__sync_add () {
	if [ $# -ne 5 ]; then
		__help
		exit 1
	fi

	# We do this in loop to catch VM's which have disks in more than one zpool
	for filesystem in $(zfs list -H -t filesystem | grep iohyve/$2 | awk '{print $1}'); do
		name=$2
		min=$3
		dest=$4
		locpool=$(echo $filesystem | cut -d '/' -f 1)
		rempool=${5:-$locpool}
		zfs set iohyve:sync="$locpool $rempool iohyve/$name $min $dest" $filesystem
	done
}

__sync_remove () {
	if [ $# -ne 2 ]; then
		__help
		exit 1
	fi

	name=$2
	for fs in $(zfs get -t filesystem -H -s local iohyve:sync | grep $name | awk '{print $1}' | sort | uniq ); do
		zfs inherit iohyve:sync $fs
	done
}

__sync_list () {
	printf "VM      SPOOL  DESTPOOL\tFILESYSTEM\tTIME\tDEST\n"
	printf "=============================================================\n"
	for dataset in $(zfs get -t filesystem -H -s local iohyve:sync | awk '{print $1}'); do
		config=$(zfs get -H -s local -o value iohyve:sync $dataset)
		poolsource=$( echo $config | cut -d ' ' -f 1 )
		pooldest=$(   echo $config | cut -d ' ' -f 2 )
		filesystem=$( echo $config | cut -d ' ' -f 3 )
		name=$(       echo $filesystem | sed -e 's/iohyve\///g')
		interval=$(   echo $config | cut -d ' ' -f 4 )
		remote=$(     echo $config | cut -d ' ' -f 5 )
		curtime=$(date +%y%m%d%H%M)
		printf "$name\t$poolsource\t$pooldest\t$filesystem\t$interval\t$remote\n"
	done
}

