#!/bin/sh

# List taps in use
__tap_list() {
	local guestlist="$(zfs list -H -o name -t filesystem | grep iohyve | cut -d'/' -f1-3)"
	echo "Listing all network taps:"
	for i in $guestlist ; do
		conprop="$(zfs get -H -o value -s local iohyve:tap $i)"
		if [ ! -z $conprop ]; then printf $i'......'$conprop'\n'; fi
	done
}

# List active taps in use
__tap_active_list() {
  echo "Listing active network taps..."
	ls /dev | grep tap
}
